[package]
name = "hbar-core"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
strum = "0.21"
strum_macros = "0.21.1"
encoding = "0.2.33"
#rayon = "1.5.1"